Repository nebari-dev/nebari, pull requests merged in 2021-03, with the labels that each got.

#352 Remove `costrouc` as the default user in qhub
  docs/source/02_get_started/04_configuration.md
  docs/source/06_developers_contrib_guide/04_local_development.md
  qhub/initialize.py
Labels: type: enhancement

#353 Jupyterhub theming using qhub-jupyterhub-theme
  RELEASE.md
  docs/source/02_get_started/04_configuration.md
  qhub/cli/deploy.py
  qhub/initialize.py
  qhub/provider/cicd/github.py
  qhub/template/cookiecutter.json
  qhub/template/{{ cookiecutter.repo_directory }}/templates/jupyterhub_config.py.j2
  setup.py
  tests/assets/config_do_additional_node_groups.yaml
  tests/assets/config_do_auth0_provision.yaml
  tests/assets/config_gcp_gpu.yaml
Labels: priority: critical :fire:, type: enhancement

#356 update instructions Terraform install
  docs/source/02_get_started/01_installation.md
  docs/source/02_get_started/03_usage.md
Labels: priority: medium, status: needs review, type: documentation

#433 Adding ability to specify node selector label for general, user, and worker
  RELEASE.md
  docs/source/02_get_started/02_setup.md
  docs/source/02_get_started/04_configuration.md
  qhub/initialize.py
  qhub/schema.py
  qhub/template/cookiecutter.json
  qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/kubernetes.tf
  qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/locals.tf
  tests/test_init.py
  tests/test_render.py
  tests/test_schema.py
Labels: status: needs review

#434 Support for namespaces with qhub deployments on kubernetes clusters
  RELEASE.md
  docs/source/02_get_started/04_configuration.md
  qhub/cli/initialize.py
  qhub/initialize.py
  qhub/schema.py
  qhub/template/cookiecutter.json
  qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/azure.tf
  qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/state.tf
  qhub/template/{{ cookiecutter.repo_directory }}/infrastructure/variables.tf
  qhub/template/{{ cookiecutter.repo_directory }}/terraform-state/main.tf
  tests/test_init.py
  tests/test_render.py
  tests/test_schema.py
Labels: status: needs review
