Repository nebari-dev/nebari, pull requests merged in 2022-05, with the labels that each got.

#856 Fix project name and domain at None
  qhub/initialize.py
Labels: needs: testing

#761 Adding name convention validator for QHub project name
  .github/workflows/test-provider.yaml
  qhub/schema.py
Labels: needs: review, area: user experience

#1271 Fix missing region from AWS provider
  qhub/stages/tf_objects.py
Labels: needs: review, provider: AWS, area: terraform

#1219 Re-enable GPU profiles for GCP/AWS
  qhub/schema.py
  qhub/stages/input_vars.py
  qhub/template/stages/02-infrastructure/gcp/modules/kubernetes/locals.tf
  qhub/template/stages/02-infrastructure/gcp/modules/kubernetes/main.tf
  qhub/template/stages/02-infrastructure/gcp/modules/kubernetes/nvidia_installer.tf
  qhub/template/stages/03-kubernetes-initialize/main.tf
  qhub/template/stages/03-kubernetes-initialize/modules/nvidia-installer/aws-nvidia-installer.tf
  qhub/template/stages/03-kubernetes-initialize/modules/nvidia-installer/gcp-nvidia-installer.tf
  qhub/template/stages/03-kubernetes-initialize/modules/nvidia-installer/variables.tf
  qhub/template/stages/03-kubernetes-initialize/variables.tf
Labels: needs: review, provider: AWS, provider: GCP, area: terraform

#1275 Fix display version behavior
  docs/source/installation/configuration.md
  qhub/stages/input_vars.py
  qhub/template/image/jupyterhub/environment.yaml
Labels: needs: review 👀

#1279 Add prefect token var to CI when needed
  docs/source/admin_guide/prefect.md
  qhub/provider/cicd/github.py
Labels: area: integration/prefect, needs: review 👀, area: user experience, area: CI 👷🏽‍♀️, area:developer-experience
