Repository nebari-dev/nebari, pull requests merged in 2022-06, with the labels that each got.

#1308 Update minio, postgresql chart repo location
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/minio/main.tf
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/postgresql/main.tf
Labels: type: bug 🐛, needs: review 👀

#1304 Fix broken AWS, set minimum desired size to 1, enable 0 scaling
  qhub/stages/input_vars.py
  qhub/template/stages/03-kubernetes-initialize/modules/cluster-autoscaler/main.tf
  qhub/template/stages/03-kubernetes-initialize/modules/extcr/main.tf
Labels: type: bug 🐛, provider: AWS, type: maintenance 🛠, area: terraform, status: merge-ready

#1321 install dask lab ext from main
  qhub/template/image/jupyterlab/environment.yaml
Labels: area: integration/Dask, area: Jupyter-extensions, status: merge-ready

#1327 Overrides default value for dask-labextension
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
Labels: status: merge-ready

#1338 Increase the default instance sizes
  docs/source/installation/configuration.md
  docs/source/installation/existing.md
  qhub/initialize.py
Labels: needs: review 👀

#1070 Add panel-serve as a CDS dashboard option
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
Labels: needs: review 👀, area: integration/dashboards

#1340 Generate QHub Costs via `infracost`
  qhub/cli/__init__.py
  qhub/cli/cost.py
  qhub/cost.py
Labels: type: enhancement 💅🏼, needs: review 👀

#1314 Add release-checklist issue template
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/testing-checklist.md
  docs/source/dev_guide/release.md
Labels: area: documentation 📖, needs: review 👀, area:developer-experience

#1341 Bump qhub-dask version to 0.4.3
  qhub/template/image/Dockerfile.dask-worker
  qhub/template/image/dask-worker/environment.yaml
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/variables.tf
  qhub/utils.py
Labels: type: maintenance 🛠, area: integration/Dask, area: dependencies 📦, status: in progress 🏗
