Repository nebari-dev/nebari, pull requests merged in 2022-11, with the labels that each got.

#1526 Remove leading `v` for release action
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/release.yaml
Labels: type: release 🏷

#1551 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/testing-checklist.md
Labels: type: file sync ♻️

#1555 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
Labels: type: file sync ♻️

#1560 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: type: file sync ♻️

#1529 Small CLI fixes
  nebari/cli/init.py
  nebari/cli/main.py
Labels: provider: Digital Ocean, area: nebari-cli

#1561 🔄 Synced file(s) with nebari-dev/.github
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/testing-checklist.md
Labels: type: file sync ♻️

#1528 Render github actions configurations as yaml
  .github/ISSUE_TEMPLATE/RFD.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/testing-checklist.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  LICENSE
  docs/_templates/announcement.html
  docs/conf.py
  docs/requirements.txt
  nebari/render.py
Labels: needs: review 👀, type: maintenance 🛠, area:developer-experience 👩🏻‍💻

#1556 Update "QHub" to "Nebari" in example notebooks
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_panel.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dask-gateway.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_nb.ipynb
Labels: area: documentation 📖

#1557 Update links to Nebari docs in guided init
  nebari/cli/init.py
Labels: type: bug 🐛, area: documentation 📖, needs: follow-up 📫

#1487 Issue-1417: Improve Dask workers placement on AWS | fixing a minor typo
  nebari/stages/input_vars.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/files/gateway_config.py
Labels: type: bug 🐛, area: integration/Dask

#1570 Update `setup-node` version
  .github/workflows/kubernetes_test.yaml
Labels: area: dependencies 📦, type: deprecation ⚰️

#1568 Facilitate CI run for contributor PR
  .cirun.yml
  .github/workflows/contributor.yaml
  .github/workflows/infracost.yml
  .github/workflows/kubernetes_test.yaml
  .github/workflows/test-provider.yaml
Labels: type: enhancement 💅🏼, area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻

#1554 Action to sync release notes with nebari-docs
  .github/release-notes-sync-config.yaml
  .github/workflows/release-notes-sync.yaml
  RELEASE.md
Labels: type: maintenance 🛠, type: release 🏷, area: community 🪴
