Repository nebari-dev/nebari, pull requests merged in 2022-09, with the labels that each got.

#1421 Add option to disable tls certificate
  qhub/schema.py
  qhub/stages/input_vars.py
  qhub/template/stages/04-kubernetes-ingress/main.tf
  qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/main.tf
  qhub/template/stages/04-kubernetes-ingress/modules/kubernetes/ingress/variables.tf
  qhub/template/stages/04-kubernetes-ingress/variables.tf
Labels: type: enhancement 💅🏼, area: user experience, needs: investigation 🔍

#1423 Nebari cli: Add files _init.py and main.py
  qhub/cli/_init.py
  qhub/cli/main.py
Labels: type: enhancement 💅🏼, status: in progress 🏗, area:developer-experience

#1425 Fixing provider=existing for local/existing
  flake.nix
  qhub/deploy.py
  qhub/destroy.py
  qhub/render.py
Labels: area: k8s, status: merge-ready

#1397 Update release, testing checklist
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/testing-checklist.md
Labels: area: documentation 📖, type: internal-pm, type: maintenance 🛠

#1429 Add `--disable-checks` flag to deploy
  qhub/cli/deploy.py
  qhub/deploy.py
Labels: type: enhancement 💅🏼, area: user experience

#1434 Add properties to middleware crd headers
  qhub/template/stages/03-kubernetes-initialize/modules/traefik_crds/main.tf
Labels: type: maintenance 🛠, area: k8s

#1437 Restart conda-store worker when new conda env is added to config.yaml
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/worker.tf
Labels: area: integration/conda-store, area: k8s

#1470 Set qhub-dask version to 0.4.4
  RELEASE.md
  qhub/constants.py
Labels: type: maintenance 🛠, area: integration/Dask

#1471 Update azurerm version
  qhub/template/stages/01-terraform-state/azure/main.tf
  qhub/template/stages/02-infrastructure/azure/versions.tf
Labels: provider: Azure, area: terraform
