Repository nebari-dev/nebari, pull requests merged in 2022-02, with the labels that each got.

#1042 Add remote state condition for 01-terraform-state provisioning
  qhub/deploy.py
  qhub/render/__init__.py
Labels: needs: review, area: architecture

#1011 DOCS: QHub 101
  docs/source/introduction/index.md
  docs/source/introduction/qhub-101.md
Labels: type: documentation

#1083 [ENH] - Update issue templates
  .github/ISSUE_TEMPLATE/bug-report---.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation---.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature-request---.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: enhancement, needs: review, area:developer-experience

#1080 [DOC]- Update contribution guidelines
  CONTRIBUTING.md
  RELEASE.md
Labels: needs: review

#1118 Adding tests to visit additional endpoints
  qhub/keycloak.py
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/variables.tf
  tests_e2e/cypress/integration/main.js
Labels: type: enhancement, type: testing, status: merge-ready

#1123 Adding tests for juypterhub-ssh, jhub-client, and vs code
  .github/workflows/kubernetes_test.yaml
  flake.nix
  setup.cfg
  tests_deployment/assets/notebook/simple.ipynb
  tests_deployment/constants.py
  tests_deployment/test_jupyterhub_ssh.py
  tests_e2e/cypress/integration/main.js
  tests_e2e/cypress/support/index.js
Labels: type: testing, needs: review

#1093 Update Keycloak docs
  docs/source/images/keycloak_add_users.png
  docs/source/images/keycloak_groups.png
  docs/source/images/keycloak_master_login.png
  docs/source/images/keycloak_new_group1.png
  docs/source/images/keycloak_new_group2.png
  docs/source/images/keycloak_new_group3.png
  docs/source/images/keycloak_root_user_account_security.png
  docs/source/images/keycloak_root_user_manage_account.png
  docs/source/images/keycloak_root_user_update_password.png
  docs/source/installation/login.md
Labels: needs: review
