Repository nebari-dev/nebari, pull requests merged in 2022-07, with the labels that each got.

#1360 Fix bug where vscode extensions are not installing
  qhub/template/image/Dockerfile.jupyterlab
  qhub/template/image/jupyterlab/environment.yaml
  qhub/template/image/jupyterlab/postBuild
  qhub/template/image/scripts/install-code-server.sh
Labels: area: user experience, area: integration/Dask, area: dependencies 📦, area: Jupyter-extensions, status: in progress 🏗

#1352 Add Python-3.10
  .github/workflows/test.yaml
  docs/index.md
  qhub/constants.py
  qhub/provider/cicd/github.py
  qhub/provider/cicd/gitlab.py
  setup.cfg
Labels: needs: review 👀, area: dependencies 📦, impact: high, needs: changes

#1379 Update Cirun.io config to use labels
  .cirun.yml
  .github/workflows/kubernetes_test.yaml
Labels: area: testing ☑️, area: CI/CD 👷🏽‍♀️
