Repository nebari-dev/nebari, pull requests merged in 2022-03, with the labels that each got.

#1130 Upgrade conda-store v0.3.10 and simplify specification of image
  qhub/stages/input_vars.py
  qhub/template/stages/07-kubernetes-services/conda-store.tf
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/variables.tf
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/variables.tf
Labels: needs: review, area: integration/conda-store

#1139 [DOC] Add `troubleshooting` docs
  docs/source/installation/login.md
  docs/source/user_guide/troubleshooting.md
  qhub/stages/checks.py
  tests/vale/styles/vocab.txt
Labels: type: documentation, needs: review

#1148 Workaround for kubernetes-client version issue
  qhub/stages/checks.py
Labels: type: bug 🐛

#1155 Minor docs clean up for v0.4.0 release
  docs/source/admin_guide/index.md
  docs/source/dev_guide/release.md
  docs/source/installation/configuration.md
  docs/source/user_guide/index.md
  pyproject.toml
  qhub/provider/cicd/github.py
  qhub/provider/cicd/gitlab.py
Labels: type: documentation

#1152 Add markdown formatter for doc wrapping
  .mdformat.toml
  .pre-commit-config.yaml
Labels: type: documentation, status: merge-ready

#1176 Adding examples to QHub jupyterlab
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/configmaps.tf
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_panel.ipynb
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_plotly.py
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_streamlit.py
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_voila.ipynb
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dask-gateway.ipynb
  qhub/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
  tests_deployment/test_jupyterhub_ssh.py
Labels: area: integration/dashboards
