Repository nebari-dev/nebari, pull requests merged in 2023-03, with the labels that each got.

#1641 Feature remove jupyterlab news
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
Labels: type: enhancement 💅🏼, area: JupyterLab, needs: tests ✅, status: approved 💪🏾

#1672 Feat GitHub actions before_script and after_script steps
  nebari/provider/cicd/github.py
  nebari/schema.py
Labels: area: user experience 👩🏻‍💻, area: CI/CD 👷🏽‍♀️

#1664 Remove examples folder
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/configmaps.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/.ipynb_checkpoints/kbatch_dask_gateway_job-checkpoint.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/.ipynb_checkpoints/kbatch_nb_job-checkpoint.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_panel.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_plotly.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_streamlit.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_voila.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dask-gateway.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_dask_gateway.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_dask_gateway_job.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_nb.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_nb_job.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
  tests_deployment/test_jupyterhub_ssh.py
Labels: area: user experience 👩🏻‍💻, status: approved 💪🏾

#1681 Update AWS force destroy script, include lingering volumes
  scripts/aws-force-destroy.sh
Labels: needs: review 👀, area: CI/CD 👷🏽‍♀️, type: maintenance 🛠, area:developer-experience 👩🏻‍💻, status: in review 👀
