Repository nebari-dev/nebari, pull requests merged in 2023-08, with the labels that each got.

#1881 Fix argo-viewer service account reference
  src/_nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
Labels: type: bug 🐛, area: integration/Argo

#1867 Framework for Nebari deployment via pytest for extensive testing
  .github/workflows/test_integration.yaml
  .gitignore
  src/_nebari/constants.py
  src/_nebari/deploy.py
  src/_nebari/provider/cloud/digital_ocean.py
  src/_nebari/stages/checks.py
  src/_nebari/utils.py
  tests/conftest.py
  tests/test_init.py
  tests/test_render.py
  tests/test_schema.py
  tests/utils.py
  tests_e2e/playwright/navigator.py
  tests_e2e/playwright/run_notebook.py
  tests_e2e/playwright/test_playwright.py
  tests_integration/README.md
  tests_integration/__init__.py
  tests_integration/conftest.py
  tests_integration/deployment_fixtures.py
  tests_integration/test_integration.py
Labels: area: testing ✅, needs: review 👀, project: JATIC

#1871 Test GCP/AWS Deployment with Pytest
  .github/workflows/kubernetes_test.yaml
  .github/workflows/test-provider.yaml
  .github/workflows/test.yaml
  .github/workflows/test_integration.yaml
  pytest.ini
  src/_nebari/keycloak.py
  tests/common/__init__.py
  tests/common/config_mod_utils.py
  tests/common/navigator.py
  tests/common/notebooks/test_notebook_output.ipynb
  tests/common/playwright_fixtures.py
  tests/common/run_notebook.py
  tests/conftest.py
  tests/tests_deployment/__init__.py
  tests/tests_deployment/assets/notebook/simple.ipynb
  tests/tests_deployment/constants.py
  tests/tests_deployment/test_dask_gateway.py
  tests/tests_deployment/test_jupyterhub_ssh.py
  tests/tests_deployment/utils.py
  tests/tests_e2e/.gitignore
  tests/tests_e2e/cypress.json
  tests/tests_e2e/cypress/.gitignore
  tests/tests_e2e/cypress/integration/main.js
  tests/tests_e2e/cypress/notebooks/BasicTest.ipynb
  tests/tests_e2e/cypress/plugins/index.js
  tests/tests_e2e/cypress/support/index.js
  tests/tests_e2e/package-lock.json
  tests/tests_e2e/package.json
  tests/tests_e2e/playwright/.env.tpl
  tests/tests_e2e/playwright/README.md
  tests/tests_e2e/playwright/test_playwright.py
  tests/tests_integration/README.md
  tests/tests_integration/__init__.py
  tests/tests_integration/conftest.py
  tests/tests_integration/deployment_fixtures.py
  tests/tests_integration/test_all_clouds.py
  tests/tests_integration/test_gpu.py
  tests/tests_integration/test_preemptible.py
  tests/tests_unit/__init__.py
  tests/tests_unit/conftest.py
  tests/tests_unit/notebooks/test-ipython-basic.ipynb
  tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-config-do-310-customauth.yaml
  tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-config-do-310.yaml
  tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-users-import.json
  tests/tests_unit/scripts/minikube-loadbalancer-ip.py
  tests/tests_unit/test_cli.py
  tests/tests_unit/test_commons.py
  tests/tests_unit/test_dependencies.py
  tests/tests_unit/test_init.py
  tests/tests_unit/test_links.py
  tests/tests_unit/test_render.py
  tests/tests_unit/test_schema.py
  tests/tests_unit/test_upgrade.py
  tests/tests_unit/utils.py
  tests/tests_unit/vale/styles/vocab.txt
  tests_e2e/playwright/run_notebook.py
  tests_e2e/playwright/test_playwright.py
  tests_integration/conftest.py
  tests_integration/deployment_fixtures.py
Labels: area: testing ✅, needs: review 👀, project: JATIC

#1887 Update upgrade command for 2023.7.2
  src/_nebari/upgrade.py
Labels: area: user experience 👩🏻‍💻

#1888 Ensure path is Path object
  src/_nebari/initialize.py
  src/_nebari/provider/git.py
Labels: type: bug 🐛, area: user experience 👩🏻‍💻

#1893 enabling viewing hidden files in jupyterlab file explorer
  src/_nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_server_config.py.tpl
Labels: area: user experience 👩🏻‍💻, area: JupyterLab

#1864 Extension mechanism AWS testing
  src/_nebari/stages/base.py
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/kubernetes_ingress/__init__.py
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/files/gateway_config.py
Labels: provider: AWS, needs: changes 🧱, project: JATIC

#1908 Fix import path in deployment tests & misc
  src/_nebari/constants.py
  src/_nebari/stages/infrastructure/__init__.py
  tests/tests_deployment/test_jupyterhub_ssh.py
Labels: area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻

#1907 pytest:ensure failure on warnings
  pytest.ini
Labels: status: blocked ⛔️, area: CI/CD 👷🏽‍♀️, type: maintenance 🛠

#1915 workaround for mixed string/posixpath error
  src/_nebari/render.py
  src/_nebari/stages/terraform_state/template/aws/main.tf
  src/_nebari/stages/terraform_state/template/aws/modules/terraform-state/main.tf
  src/_nebari/subcommands/validate.py
Labels: provider: AWS, area: nebari-cli

#1920 ENH: Remove aws cli, use boto3
  src/_nebari/provider/cloud/amazon_web_services.py
  src/_nebari/stages/infrastructure/__init__.py
Labels: provider: AWS, area:developer-experience 👩🏻‍💻

#1923 paginator for boto3 ec2 instance types
  src/_nebari/provider/cloud/amazon_web_services.py
Labels: provider: AWS

#1925 Update README.md -- fix typo.
  README.md
Labels: area: documentation 📖

#1910 Add more unit tests, add cleanup step for Digital Ocean integration test
  .gitignore
  src/_nebari/config.py
  src/_nebari/initialize.py
  src/_nebari/provider/cloud/amazon_web_services.py
  src/_nebari/provider/cloud/digital_ocean.py
  src/_nebari/stages/terraform_state/template/do/modules/terraform-state/versions.tf
  src/_nebari/utils.py
  tests/tests_integration/deployment_fixtures.py
  tests/tests_unit/test_config.py
Labels: area: testing ✅, provider: Digital Ocean, status: in review 👀

#1856 K8s 1.25 + More Improvements
  src/_nebari/stages/infrastructure/template/gcp/main.tf
  src/_nebari/stages/infrastructure/template/gcp/modules/kubernetes/main.tf
  src/_nebari/stages/infrastructure/template/gcp/modules/kubernetes/variables.tf
  src/_nebari/stages/infrastructure/template/gcp/variables.tf
  src/_nebari/stages/infrastructure/template/gcp/versions.tf
  src/_nebari/stages/kubernetes_initialize/template/modules/nvidia-installer/gcp-nvidia-installer.tf
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/01-theme.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
  tests/common/navigator.py
  tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-config-do-310-customauth.yaml
  tests/tests_unit/qhub-config-yaml-files-for-upgrade/qhub-config-do-310.yaml
Labels: type: maintenance 🛠, area: JupyterLab, area: k8s ⎈, status: in review 👀

#1905 adding lifecycle ignore to eks node group
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/main.tf
Labels: provider: AWS, area: k8s ⎈, status: in review 👀

#1931 nebari init unit tests
  src/_nebari/subcommands/init.py
  tests/tests_unit/test_cli_init.py
Labels: area: testing ✅, provider: AWS

#1933 Bug fix - JH singleuser environment getting overwritten
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
Labels: area:developer-experience 👩🏻‍💻

#1927 Allow users to specify the Azure RG to deploy into
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/terraform_state/__init__.py
  src/_nebari/stages/tf_objects.py
  src/_nebari/utils.py
Labels: area: user experience 👩🏻‍💻, provider: Azure

#1938 nebari validate unit tests
  tests/tests_unit/cli_validate/aws.error.kubernetes-version.yaml
  tests/tests_unit/cli_validate/aws.happy.yaml
  tests/tests_unit/cli_validate/azure.happy.yaml
  tests/tests_unit/cli_validate/do.happy.yaml
  tests/tests_unit/cli_validate/gcp.happy.yaml
  tests/tests_unit/cli_validate/local.error.extra-fields.yaml
  tests/tests_unit/cli_validate/local.error.project_name.yaml
  tests/tests_unit/cli_validate/local.happy.yaml
  tests/tests_unit/cli_validate/min.happy.yaml
  tests/tests_unit/test_cli_init.py
  tests/tests_unit/test_cli_validate.py
Labels: area: testing ✅, status: in review 👀, area: nebari-cli

#1903 adding openid connect provider to enable irsa feature
  src/_nebari/stages/infrastructure/template/aws/main.tf
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/locals.tf
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/main.tf
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/outputs.tf
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/variables.tf
  src/_nebari/stages/infrastructure/template/aws/outputs.tf
Labels: needs: review 👀, provider: AWS, area: k8s ⎈

#1963 nebari upgrade CLI tests
  src/_nebari/upgrade.py
  tests/tests_unit/test_cli_upgrade.py
Labels: area: testing ✅, needs: changes 🧱, area: nebari-cli

#1959 CI: Add test coverage
  .github/workflows/test.yaml
  pyproject.toml
  src/_nebari/provider/cloud/commons.py
Labels: type: enhancement 💅🏼, needs: tests ✅
