Repository nebari-dev/nebari, pull requests merged in 2023-05, with the labels that each got.

#1761 Updating heading format in release notes
  RELEASE.md
Labels: type: bug 🐛, area: documentation 📖, needs: review 👀

#1752 Update vault url
  .github/workflows/release.yaml
  .github/workflows/test-provider.yaml
Labels: type: maintenance 🛠, status: approved 💪🏾

#1734 Fix? contributor test trigger
  .github/workflows/contributor.yaml
Labels: type: bug 🐛, area: testing ✅, status: in progress 🏗

#1724 Update main with release/2023.4.1
  .github/workflows/kubernetes_test.yaml
  .github/workflows/release.yaml
  .github/workflows/test-provider.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
  README.md
  RELEASE.md
  nebari/cli/init.py
  nebari/constants.py
  nebari/initialize.py
  nebari/provider/cicd/github.py
  nebari/provider/cicd/gitlab.py
  nebari/provider/cicd/linter.py
  nebari/provider/cloud/azure_cloud.py
  nebari/render.py
  nebari/schema.py
  nebari/stages/input_vars.py
  nebari/template/stages/06-kubernetes-keycloak-configuration/permissions.tf
  nebari/template/stages/07-kubernetes-services/conda-store.tf
  nebari/template/stages/07-kubernetes-services/jupyterhub.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/server.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/configmaps.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/.ipynb_checkpoints/kbatch_dask_gateway_job-checkpoint.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/.ipynb_checkpoints/kbatch_nb_job-checkpoint.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_panel.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_plotly.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_streamlit.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dashboard_voila.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/dask-gateway.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_dask_gateway.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_dask_gateway_job.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_nb.ipynb
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/examples/kbatch_nb_job.yaml
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_notebook_config.py.tpl
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterlab/overrides.json
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/main.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/variables.tf
  nebari/template/stages/07-kubernetes-services/variables.tf
  nebari/upgrade.py
  pyproject.toml
  pytest.ini
  scripts/aws-force-destroy.py
  scripts/aws-force-destroy.sh
  tests/test_dependencies.py
  tests_deployment/test_jupyterhub_ssh.py
Labels: type: release 🏷, status: in progress 🏗

#1747 Consistent user Experience with y/N.
  nebari/cli/init.py
Labels: needs: review 👀, area: user experience 👩🏻‍💻, area: nebari-cli

#1774 turn warnings into errors with pytest
  pytest.ini
Labels: type: maintenance 🛠, status: approved 💪🏾

#1781 purge setup.cfg
  .github/workflows/kubernetes_test.yaml
  .github/workflows/test-provider.yaml
  .github/workflows/test.yaml
  .pre-commit-config.yaml
Labels: area: testing ✅, area:developer-experience 👩🏻‍💻

#1777 Overloaded dask gateway fix
  nebari/stages/input_vars.py
  nebari/template/stages/07-kubernetes-services/dask_gateway.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/files/gateway_config.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/gateway.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/dask-gateway/variables.tf
Labels: type: enhancement 💅🏼, area: integration/Dask, status: in progress 🏗

#1648 Add option to specify GKE release channel
  nebari/constants.py
  nebari/schema.py
  nebari/stages/input_vars.py
  nebari/template/stages/02-infrastructure/gcp/main.tf
  nebari/template/stages/02-infrastructure/gcp/modules/kubernetes/main.tf
  nebari/template/stages/02-infrastructure/gcp/modules/kubernetes/variables.tf
  nebari/template/stages/02-infrastructure/gcp/variables.tf
Labels: needs: review 👀, provider: GCP, type: maintenance 🛠

#1789 Update upgrade command, add RELEASE notes
  RELEASE.md
  nebari/constants.py
  nebari/upgrade.py
Labels: area: k8s ⎈, area: integration/Argo

#1771 use conda forge explicitly in conda build test
  tests/test_dependencies.py
Labels: needs: review 👀, type: maintenance 🛠, area:developer-experience 👩🏻‍💻

#1804 don't fail CI matrices fast
  .github/workflows/infracost.yml
  .github/workflows/test-provider.yaml
  .github/workflows/test.yaml
Labels: needs: review 👀, area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻

#1815 Dedent fail-fast
  .github/workflows/test-provider.yaml
  .github/workflows/test.yaml
Labels: area: CI/CD 👷🏽‍♀️

#1807 support deploying on existing vpc on aws
  nebari/stages/input_vars.py
  nebari/template/stages/02-infrastructure/aws/main.tf
  nebari/template/stages/02-infrastructure/aws/variables.tf
Labels: type: enhancement 💅🏼, provider: AWS, area: terraform 💾

#1802 purge most danlging qhub references
  README.md
  nebari/utils.py
Labels: area: documentation 📖, needs: review 👀, area:developer-experience 👩🏻‍💻

#1741 Add Argo Workflow Admission controller
  nebari/constants.py
  nebari/deploy.py
  nebari/schema.py
  nebari/stages/input_vars.py
  nebari/template/stages/05-kubernetes-keycloak/modules/kubernetes/keycloak-helm/main.tf
  nebari/template/stages/06-kubernetes-keycloak-configuration/main.tf
  nebari/template/stages/06-kubernetes-keycloak-configuration/outputs.tf
  nebari/template/stages/06-kubernetes-keycloak-configuration/permissions.tf
  nebari/template/stages/07-kubernetes-services/argo-workflows.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/argo-workflows/main.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/argo-workflows/variables.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py
Labels: type: enhancement 💅🏼, status: in progress 🏗

#1820 purge infracost CLI command / CI jobs
  .github/workflows/contributor.yaml
  .github/workflows/infracost.yml
  nebari/cli/main.py
  nebari/cost.py
Labels: needs: review 👀, type: maintenance 🛠

#1679 Add Helm chart lint tool
  .github/workflows/test_helm_charts.yaml
  scripts/helm-validate.py
Labels: area: testing ✅, area: CI/CD 👷🏽‍♀️, area: dependencies 📦, status: approved 💪🏾

#1729 don't set /etc/hosts in CI
  .github/workflows/kubernetes_test.yaml
Labels: needs: review 👀, area: CI/CD 👷🏽‍♀️

#1798 remove execute permissions on templates
  nebari/template/stages/03-kubernetes-initialize/modules/nvidia-installer/aws-nvidia-installer.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/clearml/main.tf
  nebari/template/stages/08-nebari-tf-extensions/modules/helm-extensions/main.tf
Labels: needs: review 👀, type: maintenance 🛠, area:developer-experience 👩🏻‍💻

#1799 fix deprecated file deletion
  nebari/render.py
Labels: type: bug 🐛, needs: review 👀
