Repository nebari-dev/nebari, pull requests merged in 2023-11, with the labels that each got.

#2079 CI: cleanup local integration workflow
  .github/workflows/test_local_integration.yaml
Labels: area: CI/CD 👷🏽‍♀️

#2036 ENH: check missing GCP services
  src/_nebari/provider/cloud/google_cloud.py
  tests/tests_unit/test_provider.py
Labels: type: enhancement 💅🏼, provider: GCP

#2048 ENH: use packaging for version parsing, add unit tests
  pyproject.toml
  src/_nebari/upgrade.py
  src/_nebari/version.py
  tests/tests_unit/conftest.py
  tests/tests_unit/test_upgrade.py
Labels: area: dependencies 📦, type:extension

#2033 ENH: specify required field when retrieving available gcp regions
  src/_nebari/provider/cloud/google_cloud.py
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/subcommands/init.py
Labels: provider: GCP, type: maintenance 🛠

#2092 Upgrade conda-store to 2023.10.1
  src/_nebari/constants.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py
Labels: area: integration/conda-store

#2103 Add upgrade command for 2023.11.1
  src/_nebari/upgrade.py
Labels: type: maintenance 🛠, type: release 🏷

#2107 CLN: cleanup typing and typing import in init
  src/_nebari/subcommands/init.py
Labels: type: maintenance 🛠

#2101 Remove kbatch, prefect and clearml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .pre-commit-config.yaml
  scripts/helm-validate.py
  src/_nebari/provider/cicd/github.py
  src/_nebari/stages/kubernetes_ingress/__init__.py
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/clearml.tf
  src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
  src/_nebari/stages/kubernetes_services/template/kbatch.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/Chart.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/LICENSE
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/README.md
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/charts/mongodb-10.3.7.tgz
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/charts/redis-10.9.0.tgz
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/NOTES.txt
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/_helpers.tpl
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/deployment-agent.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/deployment-agentservices.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/deployment-apiserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/deployment-elastic.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/deployment-fileserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/deployment-webserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/ingress.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/pvc-agentservices.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/pvc-apiserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/pvc-fileserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/secret-agent.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/secrets.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/service-apiserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/service-fileserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/templates/service-webserver.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/chart/values.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/ingress.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/main.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/clearml/variables.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/kbatch/main.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/kbatch/values.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/kbatch/variables.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/kbatch/versions.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/chart/.helmignore
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/chart/Chart.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/chart/templates/_helpers.tpl
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/chart/templates/prefect.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/chart/templates/secret.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/chart/values.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/main.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/values.yaml
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/prefect/variables.tf
  src/_nebari/stages/kubernetes_services/template/prefect.tf
Labels: area: dependencies 📦, needs: changes 🧱, type: deprecation ⚰️

#2102 Fix integration tests, helm-validate script
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/workflows/test_helm_charts.yaml
  README.md
  pyproject.toml
  scripts/helm-validate.py
  src/_nebari/initialize.py
Labels: area: CI/CD 👷🏽‍♀️, type: maintenance 🛠, area:developer-experience 👩🏻‍💻, needs: changes 🧱

#2112 Update upgrade instructions for 2023.11.1
  src/_nebari/upgrade.py
Labels: area: documentation 📖, type: maintenance 🛠, type: deprecation ⚰️

#2113 Update nebari-git env pins
  src/_nebari/stages/kubernetes_services/__init__.py
Labels: type: maintenance 🛠

#2114 Update release notes for 2023.11.1
  RELEASE.md
Labels: area: documentation 📖, type: release 🏷

#2115 update constants.py with current version
  .github/ISSUE_TEMPLATE/release-checklist.md
  src/_nebari/constants.py
Labels: area: dependencies 📦, type: release 🏷
