Repository nebari-dev/nebari, pull requests merged in 2023-10, with the labels that each got.

#2029 Add upgrade steps, instructions for 2023.9.1
  src/_nebari/config.py
  src/_nebari/constants.py
  src/_nebari/stages/infrastructure/template/gcp/modules/kubernetes/main.tf
  src/_nebari/stages/infrastructure/template/gcp/versions.tf
  src/_nebari/upgrade.py
  src/_nebari/utils.py
  tests/tests_unit/test_cli_upgrade.py
  tests/tests_unit/test_cli_validate.py
Labels: area: user experience 👩🏻‍💻, impact: high 🟥, project: JATIC

#2049 CI: add gcp integration test
  .github/workflows/test_gcp_integration.yaml
Labels: provider: GCP, area: CI/CD 👷🏽‍♀️

#2044 CLN: remove flake8 from dependencies
  flake.nix
  pyproject.toml
Labels: type: maintenance 🛠, area: dependencies 📦

#2060 CI: add do integration
  .github/workflows/test_do_integration.yaml
Labels: provider: Digital Ocean, area: CI/CD 👷🏽‍♀️

#2043 TYP: make all subfolders under kubernetes_services/template non-module
  src/_nebari/stages/kubernetes_services/template/modules/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/files/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/ipython/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/__init__.py
Labels: area:developer-experience 👩🏻‍💻

#2038 TYP: fix most typing errors in provider
  src/_nebari/provider/cloud/amazon_web_services.py
  src/_nebari/provider/git.py
  src/_nebari/provider/terraform.py
Labels: area:developer-experience 👩🏻‍💻

#2063 Fix link to documentation on Nebari Deployment home page
  src/_nebari/initialize.py
Labels: area: user experience 👩🏻‍💻, type: maintenance 🛠

#1996 TST: enable timeout config in playwright notebook test
  tests/common/run_notebook.py
  tests/tests_e2e/playwright/test_playwright.py
Labels: area: testing ✅, needs: review 👀, area:developer-experience 👩🏻‍💻

#2065 DEPS: sync supported python version
  README.md
  pyproject.toml
Labels: area: documentation 📖, area: dependencies 📦

#2046 Test support for Python 3.12
  .github/workflows/test.yaml
  pyproject.toml
Labels: area: testing ✅, area: dependencies 📦

#2071 CI: improve unit test workflow in CI, revert #2046
  .github/workflows/test.yaml
  pyproject.toml
Labels: area: CI/CD 👷🏽‍♀️, impact: high 🟥, area:developer-experience 👩🏻‍💻

#2027 TST: enable exact_match config in playwright notebook test
  tests/common/run_notebook.py
  tests/common/tests/test_notebook.py
Labels: area: testing ✅, needs: review 👀, area:developer-experience 👩🏻‍💻

#2073 CI: move conda build test to seperate job
  .github/workflows/test.yaml
  .github/workflows/test_aws_integration.yaml
  .github/workflows/test_conda_build.yaml
  .github/workflows/test_do_integration.yaml
  .github/workflows/test_gcp_integration.yaml
  pyproject.toml
  pytest.ini
  tests/tests_unit/test_dependencies.py
Labels: area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻

#2074 Revert conda-store to v0.4.14, #2028
  src/_nebari/constants.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py
Labels: area: dependencies 📦, area: integration/conda-store

#2066 ENH/CI: add mypy config, and CI workflow
  .github/workflows/typing.yaml
  pyproject.toml
Labels: area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻

#2080 Update upgrade for 2023.10.1
  src/_nebari/upgrade.py
  tests/tests_unit/test_cli_upgrade.py
Labels: type: maintenance 🛠

#2039 Update RELEASE notes, minor fixes
  .github/ISSUE_TEMPLATE/release-checklist.md
  .github/ISSUE_TEMPLATE/testing-checklist.md
  README.md
  RELEASE.md
  src/_nebari/constants.py
  src/_nebari/deploy.py
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/subcommands/init.py
  src/nebari/schema.py
  tests/tests_unit/test_cli_validate.py
Labels: area: documentation 📖

#2087 BUG: fix incorrect config override #2086
  src/_nebari/stages/infrastructure/__init__.py
  tests/tests_unit/test_schema.py
Labels: type: bug 🐛

#2091 Clean up main branch, removing lingering directories
  .github/workflows/kubernetes_test.yaml
  docs/source/images/argo-workflows-user-tab.png
  docs/source/user_guide/argo_workflows.md
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/dashboards/Main/cluster_information.json
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/dashboards/Main/conda_store.json
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/dashboards/Main/jupyterhub_dashboard.json
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/dashboards/Main/keycloak.json
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/dashboards/Main/traefik.json
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/monitoring/dashboards/Main/usage_report.json
  tests/conftest.py
Labels: type: maintenance 🛠

#2082 ENH: add AWS IAM permissions_boundary option #2078
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/policy.tf
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/variables.tf
  src/_nebari/stages/infrastructure/template/aws/variables.tf
  tests/tests_unit/test_schema.py
Labels: type: enhancement 💅🏼, provider: AWS
