Repository nebari-dev/nebari, pull requests merged in 2023-04, with the labels that each got.

#1689 Make idle culler settings configurable from the `nebari-config.yaml`
  nebari/schema.py
  nebari/stages/input_vars.py
  nebari/template/stages/07-kubernetes-services/jupyterhub.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/configmaps.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_notebook_config.py.tpl
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/variables.tf
  nebari/template/stages/07-kubernetes-services/variables.tf
Labels: type: enhancement 💅🏼, needs: review 👀, area: JupyterLab, needs: documentation 📖

#1662 Update pyproject dependencies and add test to ensure it builds on conda-forge
  .github/workflows/test.yaml
  pyproject.toml
  pytest.ini
  tests/test_dependencies.py
Labels: area: dependencies 📦, status: in review 👀

#1676 Retrieve secrets from Vault, fix test-provider CI
  .github/workflows/test-provider.yaml
  nebari/cli/init.py
  nebari/provider/cloud/azure_cloud.py
Labels: needs: review 👀, area: CI/CD 👷🏽‍♀️, type: maintenance 🛠

#1701 Adding newest conda-store 0.4.14 along with superadmin credentials
  nebari/constants.py
  nebari/stages/input_vars.py
  nebari/template/stages/06-kubernetes-keycloak-configuration/permissions.tf
  nebari/template/stages/07-kubernetes-services/conda-store.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/config/conda_store_config.py
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/conda-store/server.tf
Labels: needs: review 👀

#1722 Update release notes for 2023.4.1
  RELEASE.md
  nebari/constants.py
Labels: area: documentation 📖, type: release 🏷

#1699 Use --quiet flag for conda install in CI
  .github/workflows/kubernetes_test.yaml
  .github/workflows/test.yaml
Labels: needs: review 👀, type: maintenance 🛠

#1710 improve CLI tests
  tests/test_cli.py
Labels: type: enhancement 💅🏼, area: testing ✅, needs: review 👀, area: nebari-cli

#1700 improve pytest configuration
  .github/workflows/kubernetes_test.yaml
  .github/workflows/test.yaml
  pytest.ini
Labels: area: testing ✅, needs: review 👀, type: maintenance 🛠

#1721 remove lazy import
  nebari/render.py
Labels: type: maintenance 🛠

#1711 fix nebari invocation through python
  nebari/__main__.py
  tests/test_cli.py
Labels: type: bug 🐛, needs: review 👀

#1639 Update Argo Workflows to latest version
  docs/source/admin_guide/argo-workflows.md
  docs/source/images/argo-workflows-user-tab.png
  docs/source/user_guide/argo_workflows.md
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/argo-workflows/main.tf
  nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/argo-workflows/values.yaml
  nebari/upgrade.py
  tests/test_upgrade.py
Labels: type: enhancement 💅🏼, impact: high 🟥, status: in progress 🏗, needs: tests ✅, area: integration/Argo

#1753 Update secret token in release-notes-sync action
  .github/workflows/release-notes-sync.yaml
Labels: type: bug 🐛, area: documentation 📖, needs: review 👀

#1758 🔄 Synced file(s) with nebari-dev/.github
  CONTRIBUTING.md
Labels: type: file sync ♻️

#1757 Update path in release-notes-sync action
  .github/release-notes-sync-config.yaml
Labels: type: bug 🐛, needs: review 👀
