Repository nebari-dev/nebari, pull requests merged in 2023-06, with the labels that each got.

#1836 Add more InputVars schema
  src/_nebari/stages/kubernetes_initialize/__init__.py
  src/_nebari/stages/kubernetes_initialize/template/main.tf
  src/_nebari/stages/kubernetes_initialize/template/modules/cluster-autoscaler/main.tf
  src/_nebari/stages/kubernetes_initialize/template/modules/cluster-autoscaler/variables.tf
  src/_nebari/stages/kubernetes_initialize/template/modules/nvidia-installer/aws-nvidia-installer.tf
  src/_nebari/stages/kubernetes_initialize/template/modules/nvidia-installer/gcp-nvidia-installer.tf
  src/_nebari/stages/kubernetes_initialize/template/modules/nvidia-installer/variables.tf
  src/_nebari/stages/kubernetes_initialize/template/variables.tf
  src/_nebari/stages/kubernetes_keycloak/__init__.py
  src/_nebari/stages/kubernetes_keycloak/template/main.tf
  src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/main.tf
  src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/variables.tf
  src/_nebari/stages/kubernetes_keycloak/template/variables.tf
  src/_nebari/stages/kubernetes_keycloak_configuration/__init__.py
  src/_nebari/stages/terraform_state/__init__.py
Labels: needs: review 👀, area:developer-experience 👩🏻‍💻

#1819 Simplify CI
  .github/actions/publish-from-template/action.yml
  .github/actions/publish-from-template/publish-from-template.py
  .github/failed-workflow-issue-templates/test-provider.md
  .github/workflows/contributor.yaml
  .github/workflows/kubernetes_test.yaml
  .github/workflows/markdown.links.config.json
  .github/workflows/test-provider.yaml
  README.md
  pyproject.toml
Labels: area: testing ✅, area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻, needs: documentation 📖, status: approved 💪🏾

#1842 Fix edge-case where k8s_version is equal to HIGHEST_SUPPORTED_K8S_VER…
  .github/actions/publish-from-template/render_template.py
  .github/workflows/test-provider.yaml
  src/_nebari/provider/cloud/commons.py
Labels: area: CI/CD 👷🏽‍♀️, area: k8s ⎈, status: approved 💪🏾

#1841 add more configuration to enable private clusters on AWS
  src/_nebari/template/stages/02-infrastructure/aws/main.tf
  src/_nebari/template/stages/02-infrastructure/aws/modules/kubernetes/main.tf
  src/_nebari/template/stages/02-infrastructure/aws/modules/kubernetes/variables.tf
  src/_nebari/template/stages/02-infrastructure/aws/variables.tf
Labels: type: enhancement 💅🏼, provider: AWS, status: approved 💪🏾
