Repository nebari-dev/nebari, pull requests merged in 2024-06, with the labels that each got.

#2294 Explicit config
  src/_nebari/config.py
  src/_nebari/subcommands/init.py
  src/nebari/plugins.py
  src/nebari/schema.py
  tests/tests_unit/test_cli_init.py
Labels: needs: review 👀

#2512 1792 Add docstrings to `upgrade.py`
  pyproject.toml
  src/_nebari/upgrade.py
Labels: area: documentation 📖, needs: changes 🧱

#2522 set's min TLS version for azure storage account to TLS 1.2
  src/_nebari/stages/terraform_state/template/azure/modules/terraform-state/main.tf
Labels: needs: review 👀, area: security 🔐

#2288 Enable authentication by default in jupyter-server
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_server_config.py.tpl
Labels: area: security 🔐
