Repository nebari-dev/nebari, pull requests merged in 2024-08, with the labels that each got.

#2569 Enh 2451 skip conditionals
  .github/workflows/test_aws_integration.yaml
  .github/workflows/test_azure_integration.yaml
  .github/workflows/test_do_integration.yaml
  .github/workflows/test_gcp_integration.yaml
Labels: type: enhancement 💅🏼, needs: review 👀, area: CI/CD 👷🏽‍♀️, area:developer-experience 👩🏻‍💻

#2661 Use Helm Chart for JupyterHub 5.1.0
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/main.tf
Labels: area: security 🔐

#2660 Support disallowed nebari config changes
  src/_nebari/provider/terraform.py
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/terraform_state/__init__.py
  src/_nebari/stages/tf_objects.py
  src/_nebari/utils.py
  src/nebari/schema.py
  tests/tests_unit/test_stages.py
  tests/tests_unit/test_utils.py
Labels: project: JATIC

#2609 Add initial uptime metrics
  .gitignore
  src/_nebari/constants.py
  src/_nebari/provider/helm.py
  src/_nebari/provider/kubernetes.py
  src/_nebari/provider/kustomize.py
  src/_nebari/stages/base.py
  src/_nebari/stages/kubernetes_kuberhealthy/__init__.py
  src/_nebari/stages/kubernetes_kuberhealthy/template/kustomization.yaml
  src/_nebari/stages/kubernetes_kuberhealthy/template/values.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/__init__.py
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/conda-store-healthcheck.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/jupyterhub-healthcheck.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/keycloak-healthcheck.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/kustomization.yaml
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/main.tf
  src/nebari/plugins.py
Labels: type: enhancement 💅🏼, needs: review 👀, area: k8s ⎈, area: monitoring 🔍

#2644 Refactor and extend Playwright tests
  .github/workflows/test_local_integration.yaml
  tests/common/handlers.py
  tests/common/navigator.py
  tests/common/playwright_fixtures.py
  tests/common/run_notebook.py
  tests/common/tests/test_notebook.py
  tests/tests_e2e/playwright/README.md
  tests/tests_e2e/playwright/test_playwright.py
Labels: needs: review 👀

#2645 refactor jupyterhub user token retrieval within pytest
  .github/workflows/test_local_integration.yaml
  tests/tests_deployment/conftest.py
  tests/tests_deployment/constants.py
  tests/tests_deployment/keycloak_utils.py
  tests/tests_deployment/test_jupyterhub_api.py
  tests/tests_deployment/test_jupyterhub_ssh.py
  tests/tests_deployment/utils.py
Labels: needs: review 👀
