Repository nebari-dev/nebari, pull requests merged in 2024-02, with the labels that each got.

#2242 Remove `jhub-client` from pyproject.toml
  pyproject.toml
Labels: type: maintenance 🛠, area: dependencies 📦

#2258 Include permission validation step to programmatically cloned repos
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/extras/git_clone_update.sh
Labels: needs: review 👀, area: JupyterLab, type: release 🏷

#2251 Expose jupyter's preferred dir as a config option
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/configmaps.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_server_config.py.tpl
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
Labels: type: enhancement 💅🏼, area: user experience 👩🏻‍💻, area: JupyterLab

#2249 Allow to configure default settings for JupyterLab (`overrides.json`)
  .github/workflows/test_local_integration.yaml
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/jupyterhub.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/configmaps.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/variables.tf
  tests/tests_e2e/cypress/integration/main.js
  tests/tests_unit/cli_validate/min.happy.jupyterlab.default_settings.yaml
Labels: type: enhancement 💅🏼, area: JupyterLab
