Repository nebari-dev/nebari, pull requests merged in 2024-05, with the labels that each got.

#2460 Workload identity
  pyproject.toml
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/infrastructure/template/azure/main.tf
  src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/main.tf
  src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/outputs.tf
  src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/variables.tf
  src/_nebari/stages/infrastructure/template/azure/outputs.tf
  src/_nebari/stages/infrastructure/template/azure/variables.tf
  src/_nebari/stages/kubernetes_services/__init__.py
  src/_nebari/stages/kubernetes_services/template/dask_gateway.tf
  src/_nebari/stages/kubernetes_services/template/forward-auth.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/forwardauth/main.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/forwardauth/outputs.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/forwardauth/variables.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/middleware.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/variables.tf
  src/_nebari/stages/nebari_tf_extensions/__init__.py
  src/_nebari/stages/nebari_tf_extensions/template/modules/nebariextension/locals.tf
  src/_nebari/stages/nebari_tf_extensions/template/modules/nebariextension/variables.tf
  src/_nebari/stages/nebari_tf_extensions/template/tf-extensions.tf
  src/_nebari/stages/nebari_tf_extensions/template/variables.tf
Labels: needs: review 👀, provider: Azure, status: in review 👀

#2475 Fix test using a non-specific selector
  tests/common/navigator.py
  tests/common/run_notebook.py
Labels: type: bug 🐛, area: testing ✅

#2466 upgrade instructions for PR 2453
  src/_nebari/upgrade.py
Labels: DO-NOT-MERGE

#2455 Add CITATION file
  CITATION.cff
Labels: type: enhancement 💅🏼, needs: review 👀, area: community 🪴

#2061 CI: add azure integration
  .github/workflows/test_azure_integration.yaml
Labels: provider: Azure, area: CI/CD 👷🏽‍♀️
