Repository nebari-dev/nebari, pull requests merged in 2025-02, with the labels that each got.

#2939 [BUG] - Make sure to get envs when the number of envs is less than page limit
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
Labels: type: bug 🐛, area: integration/conda-store, area: integration/jhub-apps

#2902 update google terraform version, replace container registry by artifact registry
  src/_nebari/stages/infrastructure/template/gcp/main.tf
  src/_nebari/stages/infrastructure/template/gcp/modules/registry/main.tf
  src/_nebari/stages/infrastructure/template/gcp/modules/registry/variables.tf
  src/_nebari/stages/infrastructure/template/gcp/versions.tf
  src/_nebari/stages/terraform_state/template/gcp/main.tf
Labels: needs: review 👀, provider: GCP, impact: high 🟥

#2919 ignore trivy finding for public egress
  src/_nebari/stages/infrastructure/template/aws/modules/network/main.tf
Labels: needs: review 👀, provider: AWS, area: CI/CD 👷🏽‍♀️, area: security 🔐, area: networking

#2965 Update Azure's schema changes during `2025.2.1` upgrade
  src/_nebari/stages/terraform_state/__init__.py
  src/_nebari/upgrade.py
  src/_nebari/utils.py
Labels: status: approved 💪🏾

#2929 fix buffer full deadlock
  src/_nebari/utils.py
  tests/tests_unit/test_utils.py
Labels: status: approved 💪🏾

#2937 support KubeSpawner profile_options
  src/_nebari/stages/kubernetes_services/__init__.py
Labels: DO-NOT-MERGE
