Repository nebari-dev/nebari, pull requests merged in 2025-01, with the labels that each got.

#2841 [AUTO] Update CLI doc
  docs-sphinx/cli.html
Labels: "area: documentation 📖"

#2880 add authorized ip range variable for azure
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/infrastructure/template/azure/main.tf
  src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/main.tf
  src/_nebari/stages/infrastructure/template/azure/modules/kubernetes/variables.tf
  src/_nebari/stages/infrastructure/template/azure/variables.tf
Labels: needs: review 👀, provider: Azure, area: security 🔐, impact: critical, area: feature parity

#2905 Handle default value for azure addon policy
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/infrastructure/template/azure/variables.tf
Labels: type: bug 🐛, provider: Azure

#2903 Update k8s max version
  src/_nebari/constants.py
  src/_nebari/provider/cloud/commons.py
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/main.tf
  src/_nebari/stages/kubernetes_ingress/template/versions.tf
  src/_nebari/stages/kubernetes_initialize/template/versions.tf
  src/_nebari/stages/kubernetes_keycloak/template/versions.tf
  src/_nebari/stages/kubernetes_keycloak_configuration/template/versions.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/argo-workflows/versions.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/monitoring/versions.tf
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/rook-ceph/versions.tf
  src/_nebari/stages/kubernetes_services/template/versions.tf
  src/_nebari/stages/nebari_tf_extensions/template/versions.tf
Labels: needs: review 👀, area: dependencies 📦, area: k8s ⎈, area: tech-debt ⛓️

#2921 [AUTO] Update CLI doc
  docs-sphinx/cli.html
Labels: "area: documentation 📖"
