Repository nebari-dev/nebari, pull requests merged in 2025-04, with the labels that each got.

#3018 Include documentation requirement for new ENH under PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs: review 👀, area: community 🪴

#2968 refactor keycloak cli command code
  .github/workflows/test_local_integration.yaml
  src/_nebari/keycloak.py
  src/_nebari/subcommands/keycloak.py
  tests/tests_e2e/playwright/README.md
  tests/tests_unit/test_cli_keycloak.py
Labels: needs: review 👀

#2999 [AUTO] Update CLI doc
  docs-sphinx/cli.html
Labels: "area: documentation 📖"
