Repository nebari-dev/nebari, pull requests merged in 2025-03, with the labels that each got.

#2963 allow eks_public_access_cidrs to be optionally set in nebari-config.yaml
  src/_nebari/stages/infrastructure/__init__.py
  src/_nebari/stages/infrastructure/template/aws/modules/kubernetes/main.tf
Labels: needs: review 👀, provider: AWS, area: security 🔐, impact: critical, area: feature parity

#2469 Add option to customize keycloak themes
  src/_nebari/stages/kubernetes_keycloak/__init__.py
  src/_nebari/stages/kubernetes_keycloak/template/main.tf
  src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/main.tf
  src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/values.yaml
  src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/variables.tf
  src/_nebari/stages/kubernetes_keycloak/template/variables.tf
Labels: needs: review 👀

#2940 Filter environments by user access
  src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/02-spawner.py
Labels: status: approved 💪🏾

#2978 Add extra services checks to kuberhealthy
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/argo-healthcheck.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/dask-gateway-healthcheck.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/base/grafana-healthcheck.yaml
  src/_nebari/stages/kubernetes_kuberhealthy_healthchecks/template/kustomization.yaml.tmpl
  tests/tests_integration/test_all_clouds.py
Labels: needs: review 👀

#2895 Add workflow to run conda-store user journey tests
  .github/workflows/test_local_integration.yaml
  scripts/get_conda_store_token.py
  src/_nebari/keycloak.py
  src/_nebari/subcommands/keycloak.py
Labels: status: approved 💪🏾
